COMPONENT=WaterPumpAppC
BOOTLOADER=tosboot
CFLAGS += -I$(TOSDIR)/lib/net -I$(TOSDIR)/lib/net/drip
CFLAGS += -I$(TOSDIR)/lib/net/ctp
CFLAGS += -I$(TOSDIR)/lib/net/le
CFLAGS += -I../
CFLAGS += -I$(TOSDIR)/lib/printf


include $(MAKERULES)
